# Generated by Django 5.2.2 on 2025-06-08 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umbral_hipoglucemia', models.DecimalField(decimal_places=2, default=70.0, help_text='Umbral para alertas de hipoglucemia (mg/dL)', max_digits=5)),
                ('umbral_hiperglucemia', models.DecimalField(decimal_places=2, default=200.0, help_text='Umbral para alertas de hiperglucemia (mg/dL)', max_digits=5)),
                ('recordatorio_medicion_horas', models.PositiveIntegerField(default=8, help_text='Intervalo en horas para recordatorios de medición')),
                ('recordatorio_comida_horas', models.PositiveIntegerField(default=6, help_text='Intervalo en horas para recordatorios de registro de comida')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuraciones del Sistema',
                'db_table': 'configuracion_sistema',
            },
        ),
    ]
