# Generated by Django 5.2.2 on 2025-06-08 02:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_comida', models.CharField(choices=[('desayuno', 'Desayuno'), ('almuerzo', 'Almuerzo'), ('cena', 'Cena'), ('snack', 'Snack')], max_length=20)),
                ('fecha_hora', models.DateTimeField()),
                ('calorias_totales', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comida',
                'verbose_name_plural': 'Comidas',
                'db_table': 'comidas',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='TipoAlimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('categoria', models.CharField(choices=[('proteina', 'Proteína'), ('carbohidrato', 'Carbohidrato'), ('grasa', 'Grasa'), ('verdura', 'Verdura'), ('fruta', 'Fruta'), ('lacteo', 'Lácteo'), ('otro', 'Otro')], max_length=20)),
                ('indice_glucemico', models.DecimalField(blank=True, decimal_places=2, help_text='Índice glucémico del alimento (0-100)', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('calorias_por_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Alimento',
                'verbose_name_plural': 'Tipos de Alimentos',
                'db_table': 'tipos_alimentos',
                'ordering': ['categoria', 'nombre'],
                'indexes': [models.Index(fields=['categoria'], name='tipos_alime_categor_06874c_idx'), models.Index(fields=['indice_glucemico'], name='tipos_alime_indice__3f359c_idx')],
            },
        ),
        migrations.CreateModel(
            name='DetalleComida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('unidad_medida', models.CharField(choices=[('gramos', 'Gramos'), ('piezas', 'Piezas'), ('tazas', 'Tazas'), ('cucharadas', 'Cucharadas'), ('ml', 'Mililitros')], max_length=20)),
                ('comida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='nutrition.comida')),
                ('tipo_alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos_en_comidas', to='nutrition.tipoalimento')),
            ],
            options={
                'verbose_name': 'Detalle de Comida',
                'verbose_name_plural': 'Detalles de Comidas',
                'db_table': 'detalle_comidas',
            },
        ),
        migrations.AddIndex(
            model_name='comida',
            index=models.Index(fields=['usuario', '-fecha_hora'], name='comidas_usuario_d13866_idx'),
        ),
        migrations.AddIndex(
            model_name='comida',
            index=models.Index(fields=['tipo_comida'], name='comidas_tipo_co_34b4d0_idx'),
        ),
        migrations.AddIndex(
            model_name='comida',
            index=models.Index(fields=['fecha_hora'], name='comidas_fecha_h_c43730_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='detallecomida',
            unique_together={('comida', 'tipo_alimento')},
        ),
    ]
